Ensure blurring the `Combobox.Input` component closes the `Combobox`
tailwindlabs/headlessui pull request #2712
Opened 2023-08-29 09:41 UTC by RobinMalfait

This PR fixes an issue where on mobile Android the `Combobox` was not closing when pressing "Next"
on the keyboard.

This is because the "Next" button blurs the current input, but we weren't handling that properly.
This PR fixes that by also closing the `Combobox` if the `Combobox.Input` is blurred.

Fixes: #2672

2023-08-29 13:56 UTC, thecrypticace requested changes
On iOS the navigation controls only partially work:
- up/down arrows: up always works regardless of combobox
- up/down arrows: down always works regardless of combobox IF closed
- up/down arrows: down does not work on combobox IF opened

I'm not sure why this happens I was just surprised by it — I'm not sure if it's fixable. If you can get it working I think that'd be really nice.

Android the done/next button works and closes the combobox. Same on iOS too! I on the fence on whether or not I'd expect it to commit the value but I don't think that's a big deal. We can push that off until such a time that someone opens an issue.

2023-08-29 14:23 UTC, thecrypticace commented
The iOS nav thing is because it doesn't fire a blur event when there's an `absolute` element covering the input completely. Nothing we can do about that one sadly.

2023-08-29 14:23 UTC, thecrypticace approved these changes
Tested the updates on iOS and Android and it looks good.

Ship it!

2023-08-29 14:24 UTC, merged

2024-04-08 10:02 UTC, sentiasa commented
After this update, it started selecting the first element when clicked outside.

I have tried up until 1.7.19 and all releases after 1.7.16 selects the first element when clicked outside. 1.7.16 is the last working version. I had to revert back to 1.7.16