Fix outside click in nested portalled `Popover` components
tailwindlabs/headlessui pull request #3362
Opened 2024-07-04 14:55 UTC by RobinMalfait

This PR fixes an issue where nested `Popover` components that are using the `anchor` prop (and thus are portalled) are not correctly closed when clicking outside.

The issue stems from incorrect DOM node references to know whether we are allowed to click on a certain DOM element or not.

As a general recap, when an outside click happens, we need to react to it and typically use the `useOutsideClick` hook for this.

We also require the context of "allowed root containers", this means that clicking on a 3rd party toast when a dialog is open, that we allow this even though we are technically clicking outside of the dialog. This is simply because we don't have control over these elements.

We also need a reference to know what the "main tree" container is, because this is the container where your application lives and we _know_ that we are not allowed to click on anything in this container. The complex part is getting a reference to this element.

```html
<html>
<head>
   <title></title>
</head>
<body>
   <div id="app"> <-- main root container -->
      <div></div>
      <div>
         <Popover></Popover> 
      </div>
      <div></div>
   </div>

   
   <3rd-party-toast-container></3rd-party-toast-container>
</body>

<grammarly-extension></grammarly-extension>
</html>
```

Some examples:

- In case of a `Dialog`, the `Dialog` is rendered in a `Portal` which means that a DOM ref to the `Dialog` or anything inside will not point to the "main tree" node.
- In case of a `Popover` we can use the `PopoverButton` as an element that lives in the main tree. However, if you work with nested `Popover` components, and the outer `PopoverPanel` uses the `anchor` or `portal` props, then the inner `PortalButton` will not be in the main tree either because it will live in the portalled `PopoverPanel` of the parent.

This is where the `MainTreeProvider` comes in handy. This component will use the passed in `node` as the main tree node reference and pass this via the context through the React tree. This means that a nested `Popover` will still use a reference from the parent `Popover`.

In case of the `Dialog`, we wrap the `Dialog` itself with this provider which means that the provider will be in the main tree and can be used inside the portalled `Dialog`.

Another part of the `MainTreeProvider` is that if no node exists in the parent (reading from context), and no node is provided via props, then we will briefly render a hidden element, find the root node of the main tree (aka, the parent element that is a direct child of the body, `body > *`). Once we found it, we remove the hidden element again. This way we don't keep unnecessary DOM nodes around.

This also fixes another issue #3319, because we will now briefly render the hidden element to determine the main tree node.

Fixes: #3332
Fixes: #3319

2024-07-04 22:29 UTC, thecrypticace requested changes
Looks generally good just some grammar stuff and one code thing

2024-07-04 22:29 UTC, thecrypticace commented on packages/@headlessui-react/src/hooks/use-root-containers.tsx
> + * we allow clicks in 3rd party contains, but not in the parent of the "main
```suggestion
 * we allow clicks in 3rd party containers, but not in the parent of the "main
```

2024-07-04 22:29 UTC, thecrypticace commented on packages/@headlessui-react/src/hooks/use-root-containers.tsx
> + * a `Portal` (e.g.: when using the `anchor` props).
```suggestion
 * a `Portal` (e.g. when using the `anchor` props).
```

2024-07-04 22:29 UTC, thecrypticace commented on packages/@headlessui-react/src/hooks/use-root-containers.tsx
> + * rendered in a `Portal`).
```suggestion
 * `Popover`'s `PopoverPanel` component if the parent `PopoverPanel` is
 * rendered in a `Portal`.
```

2024-07-04 22:29 UTC, thecrypticace commented on packages/@headlessui-react/src/hooks/use-root-containers.tsx
> + * in the "main tree" and nested `Popover` use this button as well.
```suggestion
 * in the "main tree" and nested `Popover` will use this button as well.
```

2024-07-04 22:29 UTC, thecrypticace commented on packages/@headlessui-react/src/hooks/use-root-containers.tsx
> +            if (el) {
flip the if and return early?

2024-07-04 22:29 UTC, thecrypticace commented on packages/@headlessui-react/src/hooks/use-root-containers.tsx
> +              // `mainTreeNode` that we will be unmounting it later again.
```suggestion
              // `mainTreeNode` that we will be unmounting it later.
```

2024-07-04 23:24 UTC, RobinMalfait commented on packages/@headlessui-react/src/hooks/use-root-containers.tsx
> +            if (el) {
Good call!

2024-07-05 01:33 UTC, thecrypticace approved these changes

2024-07-05 08:11 UTC, merged